name: hoax_deteksi
description: "A new Flutter project."

publish_to: 'none'  # Avoid publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0" # Pastikan SDK Dart >= 2.17.0 untuk menggunakan fitur null safety

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_auth_web: ^5.9.0
  js: ^0.7.2
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  cloud_firestore: ^5.6.3
  emoji_picker_flutter: ^4.3.0
  http: ^1.3.0
  fl_chart: ^0.71.0
  url_launcher: ^6.1.14
  youtube_player_flutter: ^9.1.1
  animated_text_kit: ^4.2.2
  flutter_chat_bubble: ^2.0.0
  flutter_inappwebview: ^6.0.0  # Pastikan versi ini terbaru
  google_fonts: ^4.0.4
  intl: ^0.18.1
  provider: ^6.1.1
  lottie: ^2.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/Logo.png
    - assets/images/p1.jpg
    - assets/images/hoax.jpg
    - 'assets/images/hoax.json'
    - 'assets/images/jkw.png'